spring.application.name=CoverLetterCreator

#spring.datasource.url=jdbc:mysql://localhost:3306/cover_letter_creator_db
spring.datasource.username=root
#spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=mysql://yamanote.proxy.rlwy.net:55362/railway
spring.datasource.password=gcgxBqCOzqKSOQUjQlChunQiNlOEhNPd


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=yhQQqcan1CKUWsPH9JCfcwTNW9kct74CPmYTR0LLQqyJU/Pv7lmv6bJ7+D5EmnNRN1b9YezAzYSggeU43EtrpQ==

spring.security.oauth2.client.registration.github.client-id=Ov23li8biCe4gL5Ec5xU
spring.security.oauth2.client.registration.github.client-secret=7eaf2218b1280d9a9a6d39ebea423a10963b2966
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github

spring.security.oauth2.client.registration.google.client-id=287751283312-ecliqg5c11b3o10jsmdc4vavc4d3me7m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# JavaMailSender config (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangthieu006@gmail.com
spring.mail.password=vcnb ljxn abtl gcgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true